module.exports = {
  RECEIVE_TOKEN: 'RECEIVE_TOKEN',
  START_REQUEST: 'START_REQUEST',
  COMPLETE_REQUEST: 'COMPLETE_REQUEST',
  RECEIVE_CURRENT_USER: 'RECEIVE_CURRENT_USER',
  ADD_MEAL: 'ADD_MEAL',
  EDIT_MEAL: 'EDIT_MEAL',
  DELETE_MEAL: 'DELETE_MEAL',
  RESULTS_RECEIVED: 'RESULTS_RECEIVED',
}
